version: "3.8"
services:

  tracker:
    container_name: tracker
    image: zakhar0kostyshyn/tracker:1.0.1
    stdin_open: true
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    environment:
      ETHERMINE_API_KEY: ${ETHERMINE_API_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  database:
    container_name: tracker_db
    image: zakhar0kostyshyn/tracker_db:1.0.0
    stdin_open: true
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

